security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
        api_doc:
            pattern:    ^/api/doc
            security:   false
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  false
        default:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/weneedtotalk/wnttoauth/client/, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/api/v1/events, roles: [ IS_AUTHENTICATED_FULLY ], methods: [GET] }
        - { path: ^/api/v1/events, roles: [ ROLE_ADMIN ], methods: [PUT, POST, DELETE] }
        - { path: ^/api/v1/stands, roles: [ IS_AUTHENTICATED_FULLY ], methods: [GET] }
        - { path: ^/api/v1/stands, roles: [ ROLE_ADMIN ], methods: [PUT, POST, DELETE] }
        - { path: ^/api/v1/companies, roles: [ IS_AUTHENTICATED_FULLY ], methods: [GET] }
        - { path: ^/api/v1/companies, roles: [ ROLE_USER ], methods: [PUT, POST, DELETE] }
        - { path: ^/api/v1/categories, roles: [ IS_AUTHENTICATED_FULLY ], methods: [GET] }
        - { path: ^/api/v1/categories, roles: [ ROLE_USER ], methods: [POST] }
        - { path: ^/api/v1/categories, roles: [ ROLE_ADMIN ], methods: [PUT, DELETE] }
        - { path: ^/api/v1/presentations, roles: [ IS_AUTHENTICATED_FULLY ], methods: [GET] }
        - { path: ^/api/v1/presentations, roles: [ ROLE_USER ], methods: [PUT, POST, DELETE] }
        - { path: ^/api/v1/appointments, roles: [ IS_AUTHENTICATED_FULLY ], methods: [GET] }
        - { path: ^/api/v1/appointments, roles: [ ROLE_USER ], methods: [PUT, POST, DELETE] }
        - { path: ^/api/v1/users, roles: [ IS_AUTHENTICATED_FULLY ], methods: [GET, POST] }
        - { path: ^/api/v1/users, roles: [ ROLE_USER ], methods: [PUT, DELETE, PATCH] }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
