services:
    sonata.media.admin.media.manager:
        class: Sonata\MediaBundle\Admin\Manager\DoctrineMongoDBManager
        arguments: [@doctrine_mongodb, @sonata.media.manager.media]

    sonata.admin.event:
        class: Sysla\WeNeedToTalk\WnttAdminBundle\Admin\EventAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Content", label: "Events" }
        arguments:
            - ~
            - Sysla\WeNeedToTalk\WnttApiBundle\Document\Event
            - ~
        calls:
            - [ setTranslationDomain, [SyslaWeeNeedToTalkWnttAdminBundle]]

    sonata.admin.stand:
        class: Sysla\WeNeedToTalk\WnttAdminBundle\Admin\StandAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Content", label: "Stands" }
        arguments:
            - ~
            - Sysla\WeNeedToTalk\WnttApiBundle\Document\Stand
            - ~
        calls:
            - [ setTranslationDomain, [SyslaWeeNeedToTalkWnttAdminBundle]]

    sonata.admin.category:
        class: Sysla\WeNeedToTalk\WnttAdminBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Content", label: "Categories" }
        arguments:
            - ~
            - Sysla\WeNeedToTalk\WnttApiBundle\Document\Category
            - ~
        calls:
            - [ setTranslationDomain, [SyslaWeeNeedToTalkWnttAdminBundle]]

    sonata.admin.presentation:
        class: Sysla\WeNeedToTalk\WnttAdminBundle\Admin\PresentationAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Content", label: "Presentations" }
        arguments:
            - ~
            - Sysla\WeNeedToTalk\WnttApiBundle\Document\Presentation
            - ~
        calls:
            - [ setTranslationDomain, [SyslaWeeNeedToTalkWnttAdminBundle]]

    sonata.admin.company:
        class: Sysla\WeNeedToTalk\WnttAdminBundle\Admin\CompanyAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Companies", label: "Companies" }
        arguments:
            - ~
            - Sysla\WeNeedToTalk\WnttApiBundle\Document\Company
            - ~
        calls:
            - [ setTranslationDomain, [SyslaWeeNeedToTalkWnttAdminBundle]]

    sonata.admin.user:
        class: Sysla\WeNeedToTalk\WnttAdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Users", label: "Users" }
        arguments:
            - ~
            - Sysla\WeNeedToTalk\WnttUserBundle\Document\User
            - ~
        calls:
            - [ setTranslationDomain, [SyslaWeeNeedToTalkWnttAdminBundle]]

    sonata.admin.appointment:
        class: Sysla\WeNeedToTalk\WnttAdminBundle\Admin\AppointmentAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Users", label: "Appointments" }
        arguments:
            - ~
            - Sysla\WeNeedToTalk\WnttApiBundle\Document\Appointment
            - ~
        calls:
            - [ setTranslationDomain, [SyslaWeeNeedToTalkWnttAdminBundle]]
