services:
    wnttapi.manager.category:
        class: Sysla\WeNeedToTalk\WnttApiBundle\Manager\CategoryManager
        arguments: [@doctrine_mongodb]

    wnttapi.manager.company:
        class: Sysla\WeNeedToTalk\WnttApiBundle\Manager\CompanyManager
        arguments: [@doctrine_mongodb]

    wnttapi.manager.event:
        class: Sysla\WeNeedToTalk\WnttApiBundle\Manager\EventManager
        arguments: [@doctrine_mongodb]

    wnttapi.manager.presentation:
        class: Sysla\WeNeedToTalk\WnttApiBundle\Manager\PresentationManager
        arguments: [@doctrine_mongodb]

    wnttapi.manager.user:
        class: Sysla\WeNeedToTalk\WnttApiBundle\Manager\UserManager
        arguments: [@doctrine_mongodb]

    wnttapi.manager.appointment:
        class: Sysla\WeNeedToTalk\WnttApiBundle\Manager\AppointmentManager
        arguments: [@doctrine_mongodb]

    wnttapi.service.permission_verifier:
        class: Sysla\WeNeedToTalk\WnttApiBundle\Service\PermissionVerifier
        arguments: [@doctrine_mongodb]

    wnttapi.service.email_dispatcher:
        class: Sysla\WeNeedToTalk\WnttApiBundle\Service\EmailDispatcher
        arguments: [@service_container]

    wnttapi.listener.company_delete:
        class: Sysla\WeNeedToTalk\WnttApiBundle\EventListener\CompanyListener
        tags:
          - { name: doctrine_mongodb.odm.event_listener, event: preRemove }

    wnttapi.listener.category_delete:
        class: Sysla\WeNeedToTalk\WnttApiBundle\EventListener\CategoryListener
        tags:
          - { name: doctrine_mongodb.odm.event_listener, event: preRemove }

    wnttapi.listener.presentation_persist:
        class: Sysla\WeNeedToTalk\WnttApiBundle\EventListener\PresentationListener
        tags:
          - { name: doctrine_mongodb.odm.event_listener, event: prePersist }
